rootProject.name = "core"
include("annotations")
include("files")
include("functions")
include("i18n")
include("nbt")
include("paper")
include("adapters")
include("sql")
include("utils")
include("version-checker")
